version: '1.0'
epic: '1118'
generated_at: '2026-06-02T22:03:30Z'
source:
  spec_file: epics/1118/specs/Spec_example.xlsx
  spec_sheet: PROJECT
table: PROJECT
fields:
- name: proj_id
  type: number
  nullable: false
  description: Unique ID
  primary_key: true
- name: column1
  type: boolean
  nullable: true
  description: Desc1
  primary_key: true
- name: column2
  type: timestamp
  nullable: true
  description: Desc2
- name: column3
  type: string
  nullable: true
  description: Desc3
  max_length: 384
- name: column4
  type: string
  nullable: true
  description: Desc4
  max_length: 384
