column_mapping:
  name:
    spec_name: Champ dans extract
    value_required: true
  type:
    spec_name: Type
    value_required: true
  description:
    spec_name: Description
    required: false
  table:
    spec_name: Table
    required: false
  nullable:
    spec_name: Obligatoire
    value_required: true
    values:
      "true":  ["non", "no", "false", "0", "n"]
      "false": ["oui", "yes", "true", "1", "o", "y"]

keys:
  sheet_name: "Clés unitaires"
  column_mapping:
    table_name:
      spec_name: "Table"
      value_required: true
    primary_key:
      spec_name: "Clé primaire"
      value_required: true
      separator: "&"
    foreign_key:
      spec_name: "Clé étrangère"
      separator: ","
      allow_violations: true
    comments:
      spec_name: "Commentaires"
      required: false

joins:
  sheet_name: "Clés de jointure"
  column_mapping:
    source_table:
      spec_name: "Table Source"
      value_required: true
    target_table:
      spec_name: "Table Cible"
      value_required: true
    source_column:
      spec_name: "Clé Jointure Source"
      value_required: true
    target_column:
      spec_name: "Clé Jointure Cible"
      value_required: true
    join_type:
      spec_name: "Type de Jointure"
      value_required: true
    cardinality:
      spec_name: "Cardinalité"
    comment:
      spec_name: "Commentaire"
      required: false
    description:
      spec_name: "Description / règle métier"
      required: false
