mappings:
  - canonical: varchar
    aliases: [varchar, char, string, texte, text]
    parameter: max_length
  - canonical: integer
    aliases: [int, integer, bigint, smallint, entier]
  - canonical: double
    aliases: [double, numeric, "réel", real, decimal, number]
  - canonical: float
    aliases: [float]
    parameter: precision
  - canonical: boolean
    aliases: ["booléen", boolean, bool]
    data_values:
      "true":  [true, "true", "vrai", "oui", "1", "y", "yes"]
      "false": [false, "false", "faux", "non", "0", "n", "no"]
  - canonical: date
    aliases: [date]
  - canonical: timestamp
    aliases: ["date horodatée", timestamp, datetime]
